### ISSUE TITLE
output format unknown?

### ISSUE THREAD

**Issue by novotechsoft** [mac999/landxml_parser#1]
Hello
Thanks for your great program. I tried it and converted a few landxml files to json. I expected that the output file should be TopoJSON format but it looks like the output file is not readable by topojson viewers. Can you please clarify what json format do you convert to? 
My goal is to load LandXML files and eventually load data into Azure maps (for example in GeoJSON or TopoJSON formats).

Thanks
A

**Comment by mac999** [comment]
Hi. 

As you know, LandXML is consists of align, profile, x-section information. GeoJSON has polyline, multipoly, polygon (https://geojson.org/, https://github.com/topojson/topojson-specification). To represent the to GeoJSON, you need to execute the bleow step. 
1. parsing landxml (by using this library). 
2. calculate the geometry model from the align, profile, x-section mathmatically. 
3. save GeoJSON using the geometry model.

**Comment by novotechsoft** [comment]
Are you interested in completing steps 2 and 3 of your message (calculate + generate GeoJSON)? If yes, we may be able to pay you for this. If you are interested please email me at alireza@novotechsoftware.com

**Comment by mac999** [comment]
Thanks for your interests related to this library. I sent email to you.
